import turtle
screen = turtle.Screen()
screen.screensize(500,500)
t=turtle.Turtle()
t.speed(0)
#slide1
screen.bgcolor("pink")
t.penup()
t.goto(0, 100)
t.pendown()
t.write("All About", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(0, -100)
t.pendown()
t.write("Angelina", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(-200,0)
t.pendown()
t.pencolor('green')
t.pensize(8)
t.goto(-200,-100)
t.pensize(1)
t.penup()
t.goto(-200,0)
t.pendown()


t.pencolor('purple')
t.fillcolor('purple')
t.begin_fill()
t.circle(25)
t.setheading(90)
t.circle(25)
t.setheading(180)
t.circle(25)
t.setheading(270)
t.circle(25)
t.end_fill()
t.penup()
t.goto(-200,-15)
t.pendown()
t.setheading(0)
t.fillcolor('yellow')
t.begin_fill()
t.circle(15)
t.end_fill()


t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape('imagenew2.gif')
t.shape('imagenew2.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200, 0)
t.pendown()
screen.addshape('sports2.gif')
t.shape('sports2.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(0, -200)
t.pendown()
t.write("Press Enter to Continue", font=('arial', 30, "normal"), align='center')

round = input("Press Enter To Continue: ")
t.clear()
#slide2
screen.bgcolor("purple")
t.pencolor('white')

t.penup()
t.goto(0, 100)
t.pendown()
t.write("Favorite Food", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(-25,150)
t.pendown()
t.fillcolor("tan")
t.begin_fill()
t.goto(25,150)
t.goto(25,250)
t.goto(-25,150)
t.end_fill()

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape('pastaedit.gif')
t.shape('pastaedit.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(1, -60)
t.pendown()
t.write("Pasta", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(200, 0)
t.pendown()
screen.addshape('taco.gif')
t.shape('taco.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(200, -100)
t.pendown()
t.write("Tacos", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(-200, 0)
t.pendown()
screen.addshape('chick.gif')
t.shape('chick.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-200, -60)
t.pendown()
t.write("Chicken Tenders", font=('arial', 20, "normal"), align='center')
t.penup()
t.goto(0, -200)
t.pendown()
t.write("Press Enter to Continue", font=('arial', 30, "normal"), align='center')

round = input("Press Enter To Continue: ")
t.clear()
#slide3
screen.bgcolor("lightblue")
t.pencolor('white')

t.penup()
t.goto(0, 100)
t.pendown()
t.write("Favorite Hobbies", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(0,-200)
t.pendown()

t.begin_fill()
t.circle(50)
t.end_fill()
t.fillcolor('blue')
t.begin_fill()
t.circle(50,120)
t.end_fill()
t.fillcolor('green')
t.begin_fill()
t.circle(50,120)
t.end_fill()
t.fillcolor('orange')
t.begin_fill()
t.circle(50,120)
t.end_fill()

t.penup()
t.goto(52, 0)
t.pendown()
screen.addshape('soccer.gif')
t.shape('soccer.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(75, -60)
t.pendown()
t.write("Soccer", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(-200, 0)
t.pendown()
screen.addshape('baking.gif')
t.shape('baking.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-200, -60)
t.pendown()
t.write("Baking", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(200, 0)
t.pendown()
screen.addshape('music.gif')
t.shape('music.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(200, -60)
t.pendown()
t.write("Music", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(-100, 0)
t.pendown()
screen.addshape('shopping.gif')
t.shape('shopping.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-75, -60)
t.pendown()
t.write("Shopping", font=('arial', 20, "normal"), align='center')
t.penup()
t.goto(0, -300)
t.pendown()
t.write("Press Enter to Continue", font=('arial', 30, "normal"), align='center')

round = input("Press Enter To Continue: ")
t.clear()
#slide4
screen.bgcolor("coral")
t.pencolor('white')

t.penup()
t.goto(0, 100)
t.pendown()
t.write("Favorite Movie", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(0, -200)
t.pendown()
t.fillcolor('white')
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(0, 0)
t.pendown()
screen.addshape('movie.gif')
t.shape('movie.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(15,-75)
t.pendown()
t.write("Step Brothers", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(-100, 0)
t.pendown()
screen.addshape('frog.gif')
t.shape('frog.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-150, -80)
t.pendown()
t.write("Princess", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(0, -300)
t.pendown()
t.write("Press Enter to Continue", font=('arial', 30, "normal"), align='center')

round = input("Press Enter To Continue: ")
t.clear()
#slide4
screen.bgcolor("navy")
t.pencolor('white')

t.penup()
t.goto(0, 100)
t.pendown()
t.write("Favorite Sport", font=('arial', 30, "normal"), align='center')

t.penup()
t.goto(-25, 150)
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.end_fill()

t.penup()
t.goto(50, 10)
t.pendown()
screen.addshape('soccerplayer.gif')
t.shape('soccerplayer.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(15,-75)
t.pendown()
t.write("Sport", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(-100, 0)
t.pendown()
screen.addshape('hockey.gif')
t.shape('hockey.gif')
t.stamp()
t.shape('classic')
t.penup()
t.goto(-135, -85)
t.pendown()
t.write("Hockey", font=('arial', 20, "normal"), align='center')

t.penup()
t.goto(0, -200)
t.pendown()
t.write("Press Enter to Continue", font=('arial', 30, "normal"), align='center')

round = input("Press Enter To Continue: ")









turtle.done()